/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.Profile;
import java.io.File;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author aishw
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    Profile profile;
    public CreateJPanel(Profile profile) {
        initComponents();
        this.profile = profile;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblDate_of_Birth = new javax.swing.JLabel();
        lblGeographic_data1 = new javax.swing.JLabel();
        lblTelephone_Number = new javax.swing.JLabel();
        lblFAX_number1 = new javax.swing.JLabel();
        lblEmail_address = new javax.swing.JLabel();
        lblSocial_Security_Number = new javax.swing.JLabel();
        lblMedical_record_number = new javax.swing.JLabel();
        lblHealth_Plan_Beneficiary_Number = new javax.swing.JLabel();
        lblBank_Account_Number = new javax.swing.JLabel();
        lblCertificate_or_License_Number = new javax.swing.JLabel();
        lblVehicle_identifier_and_Serial_number_including_license_plate = new javax.swing.JLabel();
        lblDevice_Identifiers_and_Serial_number = new javax.swing.JLabel();
        lblLinkedIn = new javax.swing.JLabel();
        lblInternet_Protocol_Address = new javax.swing.JLabel();
        lblBiometric_Photo = new javax.swing.JLabel();
        lblUnique_Identifying_Number_or_Code = new javax.swing.JLabel();
        txtGeographic_data = new javax.swing.JTextField();
        txtTelephone_Number = new javax.swing.JTextField();
        txtFAX_number = new javax.swing.JTextField();
        txtEmail_address = new javax.swing.JTextField();
        txtSocial_Security_Number = new javax.swing.JTextField();
        txtMedical_record_number = new javax.swing.JTextField();
        txtHealth_Plan_Beneficiary_Number = new javax.swing.JTextField();
        txtBank_Account_Number = new javax.swing.JTextField();
        txtCertificate_or_License_Number = new javax.swing.JTextField();
        txtVehicle_identifier_and_Serial_number_including_license_plate = new javax.swing.JTextField();
        txtDevice_Identifiers_and_Serial_number = new javax.swing.JTextField();
        txtLinkedIn = new javax.swing.JTextField();
        txtInternet_Protocol_Address = new javax.swing.JTextField();
        txtUnique_Identifying_Number_or_Code = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        lblError_Name = new javax.swing.JLabel();
        lblEmail_Adr = new javax.swing.JLabel();
        lblTele_Num = new javax.swing.JLabel();
        lblGeography = new javax.swing.JLabel();
        lblFAX = new javax.swing.JLabel();
        lblSSN = new javax.swing.JLabel();
        lblMRN = new javax.swing.JLabel();
        lblHPBN = new javax.swing.JLabel();
        lblBankAC = new javax.swing.JLabel();
        lblCLN = new javax.swing.JLabel();
        lblVIN_Num = new javax.swing.JLabel();
        lblDIN = new javax.swing.JLabel();
        lblLinkedIN = new javax.swing.JLabel();
        lblIP = new javax.swing.JLabel();
        lblUIN = new javax.swing.JLabel();
        jButton_Upload = new javax.swing.JButton();
        lblImage = new javax.swing.JLabel();
        txtdateOfBirth = new com.toedter.calendar.JDateChooser();

        lblTitle.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Person Profile");
        lblTitle.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 255), 4, true));

        lblName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblName.setText("Name:");

        lblDate_of_Birth.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblDate_of_Birth.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDate_of_Birth.setText("Date_of_Birth:");

        lblGeographic_data1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblGeographic_data1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblGeographic_data1.setText("Address");

        lblTelephone_Number.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblTelephone_Number.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTelephone_Number.setText("Telephone_Number:");

        lblFAX_number1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblFAX_number1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFAX_number1.setText("FAX_number:");

        lblEmail_address.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblEmail_address.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEmail_address.setText("Email_address:");

        lblSocial_Security_Number.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblSocial_Security_Number.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSocial_Security_Number.setText("Social_Security_Number:");

        lblMedical_record_number.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblMedical_record_number.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMedical_record_number.setText("Medical_record_number:");

        lblHealth_Plan_Beneficiary_Number.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblHealth_Plan_Beneficiary_Number.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblHealth_Plan_Beneficiary_Number.setText("Health_Plan_Beneficiary_Number:");

        lblBank_Account_Number.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblBank_Account_Number.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBank_Account_Number.setText("Bank_Account_Number:");

        lblCertificate_or_License_Number.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblCertificate_or_License_Number.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCertificate_or_License_Number.setText("License_Number:");

        lblVehicle_identifier_and_Serial_number_including_license_plate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblVehicle_identifier_and_Serial_number_including_license_plate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblVehicle_identifier_and_Serial_number_including_license_plate.setText("Vehicle_identifier_and_Serial_number_including_license_plate:");

        lblDevice_Identifiers_and_Serial_number.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblDevice_Identifiers_and_Serial_number.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDevice_Identifiers_and_Serial_number.setText("Device_Identifiers_and_Serial_number:");

        lblLinkedIn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblLinkedIn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLinkedIn.setText("LinkedIn:");

        lblInternet_Protocol_Address.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblInternet_Protocol_Address.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblInternet_Protocol_Address.setText("Internet_Protocol_Address:");

        lblBiometric_Photo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblBiometric_Photo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBiometric_Photo.setText("Biometric_Photo");

        lblUnique_Identifying_Number_or_Code.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblUnique_Identifying_Number_or_Code.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUnique_Identifying_Number_or_Code.setText("Unique_Identifying_Number_or_Code:");

        txtGeographic_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGeographic_dataActionPerformed(evt);
            }
        });
        txtGeographic_data.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGeographic_dataKeyReleased(evt);
            }
        });

        txtTelephone_Number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelephone_NumberActionPerformed(evt);
            }
        });
        txtTelephone_Number.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelephone_NumberKeyReleased(evt);
            }
        });

        txtFAX_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFAX_numberActionPerformed(evt);
            }
        });
        txtFAX_number.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFAX_numberKeyReleased(evt);
            }
        });

        txtEmail_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmail_addressActionPerformed(evt);
            }
        });
        txtEmail_address.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmail_addressKeyReleased(evt);
            }
        });

        txtSocial_Security_Number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSocial_Security_NumberActionPerformed(evt);
            }
        });
        txtSocial_Security_Number.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSocial_Security_NumberKeyReleased(evt);
            }
        });

        txtMedical_record_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedical_record_numberActionPerformed(evt);
            }
        });
        txtMedical_record_number.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMedical_record_numberKeyReleased(evt);
            }
        });

        txtHealth_Plan_Beneficiary_Number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHealth_Plan_Beneficiary_NumberActionPerformed(evt);
            }
        });
        txtHealth_Plan_Beneficiary_Number.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtHealth_Plan_Beneficiary_NumberKeyReleased(evt);
            }
        });

        txtBank_Account_Number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBank_Account_NumberActionPerformed(evt);
            }
        });
        txtBank_Account_Number.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBank_Account_NumberKeyReleased(evt);
            }
        });

        txtCertificate_or_License_Number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCertificate_or_License_NumberActionPerformed(evt);
            }
        });
        txtCertificate_or_License_Number.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCertificate_or_License_NumberKeyReleased(evt);
            }
        });

        txtVehicle_identifier_and_Serial_number_including_license_plate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVehicle_identifier_and_Serial_number_including_license_plateActionPerformed(evt);
            }
        });
        txtVehicle_identifier_and_Serial_number_including_license_plate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtVehicle_identifier_and_Serial_number_including_license_plateKeyReleased(evt);
            }
        });

        txtDevice_Identifiers_and_Serial_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDevice_Identifiers_and_Serial_numberActionPerformed(evt);
            }
        });
        txtDevice_Identifiers_and_Serial_number.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDevice_Identifiers_and_Serial_numberKeyReleased(evt);
            }
        });

        txtLinkedIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLinkedInActionPerformed(evt);
            }
        });
        txtLinkedIn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLinkedInKeyReleased(evt);
            }
        });

        txtInternet_Protocol_Address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInternet_Protocol_AddressActionPerformed(evt);
            }
        });
        txtInternet_Protocol_Address.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtInternet_Protocol_AddressKeyReleased(evt);
            }
        });

        txtUnique_Identifying_Number_or_Code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnique_Identifying_Number_or_CodeActionPerformed(evt);
            }
        });
        txtUnique_Identifying_Number_or_Code.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUnique_Identifying_Number_or_CodeKeyReleased(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(255, 255, 255));
        btnSave.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNameKeyReleased(evt);
            }
        });

        lblError_Name.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        lblError_Name.setForeground(new java.awt.Color(255, 0, 0));

        lblEmail_Adr.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        lblEmail_Adr.setForeground(new java.awt.Color(255, 0, 51));

        lblTele_Num.setForeground(new java.awt.Color(255, 0, 51));

        lblGeography.setForeground(new java.awt.Color(255, 0, 51));

        lblFAX.setForeground(new java.awt.Color(255, 0, 51));

        lblSSN.setForeground(new java.awt.Color(255, 0, 0));

        lblMRN.setForeground(new java.awt.Color(255, 0, 51));

        lblHPBN.setForeground(new java.awt.Color(255, 0, 51));

        lblBankAC.setForeground(new java.awt.Color(255, 0, 0));

        lblCLN.setForeground(new java.awt.Color(255, 0, 51));

        lblVIN_Num.setForeground(new java.awt.Color(255, 0, 51));

        lblDIN.setForeground(new java.awt.Color(255, 0, 51));

        lblLinkedIN.setForeground(new java.awt.Color(255, 0, 51));

        lblIP.setForeground(new java.awt.Color(255, 0, 51));

        lblUIN.setForeground(new java.awt.Color(255, 0, 51));

        jButton_Upload.setText("Uplaod");
        jButton_Upload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_UploadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDate_of_Birth, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSocial_Security_Number, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMedical_record_number, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHealth_Plan_Beneficiary_Number)
                    .addComponent(lblBank_Account_Number)
                    .addComponent(lblCertificate_or_License_Number)
                    .addComponent(lblLinkedIn)
                    .addComponent(lblInternet_Protocol_Address)
                    .addComponent(lblBiometric_Photo)
                    .addComponent(lblUnique_Identifying_Number_or_Code)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGeographic_data1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelephone_Number, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail_address, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFAX_number1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblVehicle_identifier_and_Serial_number_including_license_plate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblDevice_Identifiers_and_Serial_number)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtEmail_address, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblEmail_Adr, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCertificate_or_License_Number, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCLN, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtDevice_Identifiers_and_Serial_number, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDIN, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtdateOfBirth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtTelephone_Number, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                                    .addComponent(txtFAX_number, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                                    .addComponent(txtSocial_Security_Number, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                                    .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                                    .addComponent(txtMedical_record_number, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                                    .addComponent(txtLinkedIn, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                                    .addComponent(txtInternet_Protocol_Address, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                                    .addComponent(txtUnique_Identifying_Number_or_Code, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                                    .addComponent(txtGeographic_data, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                                    .addComponent(txtHealth_Plan_Beneficiary_Number, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                                    .addComponent(txtBank_Account_Number, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                                    .addComponent(txtVehicle_identifier_and_Serial_number_including_license_plate, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblGeography, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblError_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblTele_Num, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblFAX, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblMRN, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblHPBN, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblBankAC, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblVIN_Num, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblLinkedIN, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblIP, javax.swing.GroupLayout.DEFAULT_SIZE, 1536, Short.MAX_VALUE))
                                        .addGap(63, 63, 63))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblUIN, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jButton_Upload, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblImage)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(423, 423, 423)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 1138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblName, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGeographic_data1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGeographic_data, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblError_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblGeography, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtdateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDate_of_Birth, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTele_Num, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblTelephone_Number, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtTelephone_Number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFAX_number1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFAX_number, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFAX, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmail_address, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmail_Adr, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSocial_Security_Number, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtSocial_Security_Number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtMedical_record_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblMedical_record_number, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblMRN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(lblHealth_Plan_Beneficiary_Number, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblHPBN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtHealth_Plan_Beneficiary_Number, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtBank_Account_Number)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblBank_Account_Number)
                                            .addComponent(lblBankAC, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCertificate_or_License_Number, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCertificate_or_License_Number, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCLN, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtVehicle_identifier_and_Serial_number_including_license_plate, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblVehicle_identifier_and_Serial_number_including_license_plate, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblVIN_Num, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDevice_Identifiers_and_Serial_number, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                            .addComponent(lblDevice_Identifiers_and_Serial_number, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblDIN, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLinkedIN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblLinkedIn, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtLinkedIn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtInternet_Protocol_Address, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInternet_Protocol_Address, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBiometric_Photo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_Upload, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblImage))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUIN, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUnique_Identifying_Number_or_Code, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUnique_Identifying_Number_or_Code, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSave)
                .addGap(305, 305, 305))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtGeographic_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGeographic_dataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGeographic_dataActionPerformed

    private void txtTelephone_NumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelephone_NumberActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_txtTelephone_NumberActionPerformed

    private void txtFAX_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFAX_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFAX_numberActionPerformed

    private void txtEmail_addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmail_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmail_addressActionPerformed

    private void txtSocial_Security_NumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSocial_Security_NumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSocial_Security_NumberActionPerformed

    private void txtMedical_record_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedical_record_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedical_record_numberActionPerformed

    private void txtHealth_Plan_Beneficiary_NumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHealth_Plan_Beneficiary_NumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHealth_Plan_Beneficiary_NumberActionPerformed

    private void txtBank_Account_NumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBank_Account_NumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBank_Account_NumberActionPerformed

    private void txtCertificate_or_License_NumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCertificate_or_License_NumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCertificate_or_License_NumberActionPerformed

    private void txtVehicle_identifier_and_Serial_number_including_license_plateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVehicle_identifier_and_Serial_number_including_license_plateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVehicle_identifier_and_Serial_number_including_license_plateActionPerformed

    private void txtDevice_Identifiers_and_Serial_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDevice_Identifiers_and_Serial_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDevice_Identifiers_and_Serial_numberActionPerformed

    private void txtLinkedInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLinkedInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLinkedInActionPerformed

    private void txtInternet_Protocol_AddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInternet_Protocol_AddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInternet_Protocol_AddressActionPerformed

    private void txtUnique_Identifying_Number_or_CodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnique_Identifying_Number_or_CodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnique_Identifying_Number_or_CodeActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
       
        if (txtName.getText().isEmpty() ||
            txtGeographic_data.getText().isEmpty() ||
//            txtdateOfBirth.getDate().isEmpty() &&
            txtTelephone_Number.getText().isEmpty() ||
            txtFAX_number.getText().isEmpty() ||
            txtEmail_address.getText().isEmpty() ||
            txtSocial_Security_Number.getText().isEmpty() ||
            txtMedical_record_number.getText().isEmpty() ||
            txtHealth_Plan_Beneficiary_Number.getText().isEmpty() ||
            txtBank_Account_Number.getText().isEmpty() ||
            txtCertificate_or_License_Number.getText().isEmpty() ||
            txtVehicle_identifier_and_Serial_number_including_license_plate.getText().isEmpty() ||
            txtLinkedIn.getText().isEmpty() ||
            txtInternet_Protocol_Address.getText().isEmpty() ||
            lblImage.getText().equals("") ||
            txtUnique_Identifying_Number_or_Code.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Enter all fields");    
        } else {
            if(!lblError_Name.getText().equals("") ||
               !lblGeography.getText().equals("") ||
               !lblTele_Num.getText().equals("") ||
               !lblFAX.getText().equals("") ||
               !lblEmail_Adr.getText().equals("") ||
               !lblSSN.getText().equals("") ||
               !lblMRN.getText().equals("") ||
               !lblHPBN.getText().equals("") ||
               !lblBankAC.getText().equals("") ||
               !lblVIN_Num.getText().equals("") ||
               !lblDIN.getText().equals("") ||
               !lblLinkedIN.getText().equals("") ||
               !lblIP.getText().equals("") ||
               !lblUIN.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Correct the Errors!"); 
            }else{
                profile.setName(txtName.getText());
                profile.setGeographic_data(txtGeographic_data.getText());
                profile.setDate_of_Birth(txtdateOfBirth.getDate());
                profile.setTelephone_Number((Long.parseLong(txtTelephone_Number.getText())));
                profile.setFAX_number((Long.parseLong(txtFAX_number.getText())));
                profile.setEmail_address(txtEmail_address.getText());
                profile.setSocial_Security_Number((txtSocial_Security_Number.getText()));
                profile.setMedical_record_number((Long.parseLong(txtMedical_record_number.getText())));
                profile.setHealth_Plan_Beneficiary_Number((Long.parseLong(txtHealth_Plan_Beneficiary_Number.getText())));
                profile.setBank_Account_Number((Long.parseLong(txtBank_Account_Number.getText())));
                profile.setCertificate_or_License_Number((Long.parseLong(txtCertificate_or_License_Number.getText())));
                profile.setVehicle_identifier_and_Serial_number_including_license_plate(txtVehicle_identifier_and_Serial_number_including_license_plate.getText());
                profile.setDevice_Identifiers_and_Serial_number((Integer.parseInt(txtDevice_Identifiers_and_Serial_number.getText())));
                profile.setLinkedIn(txtLinkedIn.getText());
                profile.setInternet_Protocol_Address(txtInternet_Protocol_Address.getText());
                profile.setUnique_identifier((Long.parseLong(txtUnique_Identifying_Number_or_Code.getText())));

                JOptionPane.showMessageDialog(this, "Product Information Saved");
        }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z ]{0,30}$";
        Pattern PName = Pattern.compile(PATTERN);
        Matcher MName = PName.matcher(txtName.getText());
        
        if(!MName.matches()){
            lblError_Name.setText("Naming Incorrect, Only Letters allowed!");
        }
        else{
            lblError_Name.setText("");
        }

    }//GEN-LAST:event_txtNameKeyReleased

    private void txtEmail_addressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmail_addressKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z0-9._]{0,30}[@][a-zA-Z0-9]{0,10}[.][a-zA-Z]{0,5}$";
        Pattern PEmail = Pattern.compile(PATTERN);
        Matcher MEmail = PEmail.matcher(txtEmail_address.getText());
        
        if(!MEmail.matches()){
            lblEmail_Adr.setText("Email Address Incorrect!");
        }
        else{
            lblEmail_Adr.setText("");
        }
    }//GEN-LAST:event_txtEmail_addressKeyReleased

    private void txtTelephone_NumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelephone_NumberKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[0-9]{0,10}$";
        Pattern PTele_Num = Pattern.compile(PATTERN);
        Matcher MTele_Num = PTele_Num.matcher(txtTelephone_Number.getText());
        
        if(!MTele_Num.matches()){
            lblTele_Num.setText("Phone Num Incorrect!");
        }
        else{
            lblTele_Num.setText("");
        }
    }//GEN-LAST:event_txtTelephone_NumberKeyReleased

    private void txtSocial_Security_NumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSocial_Security_NumberKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^(?!666|000|9\\d{2})\\d{3}-(?!00)\\d{2}-(?!0{4})\\d{4}$";
        Pattern PSSN = Pattern.compile(PATTERN);
        Matcher MSSN = PSSN.matcher(txtSocial_Security_Number.getText());
        
        if(!MSSN.matches()){
            lblSSN.setText("Correct SSN needed!");
        }
        else{
            lblSSN.setText("");
        }
    }//GEN-LAST:event_txtSocial_Security_NumberKeyReleased

    private void txtFAX_numberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFAX_numberKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[0-9]{0,7}$";
        Pattern PFAX = Pattern.compile(PATTERN);
        Matcher MFAX = PFAX.matcher(txtFAX_number.getText());
        
        if(!MFAX.matches()){
            lblFAX.setText("Enter Correct FAX Number!");
        }
        else{
            lblFAX.setText("");
        }
    }//GEN-LAST:event_txtFAX_numberKeyReleased

    private void txtMedical_record_numberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMedical_record_numberKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[0-9]{0,18}$";
        Pattern PMRN = Pattern.compile(PATTERN);
        Matcher MMRN = PMRN.matcher(txtMedical_record_number.getText());
        
        if(!MMRN.matches()){
            lblMRN.setText("Correct MRN needed!");
        }
        else{
            lblMRN.setText("");
        }
    }//GEN-LAST:event_txtMedical_record_numberKeyReleased

    private void txtBank_Account_NumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBank_Account_NumberKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[0-9]{0,15}$";
        Pattern PBAC = Pattern.compile(PATTERN);
        Matcher MBAC = PBAC.matcher(txtBank_Account_Number.getText());
        
        if(!MBAC.matches()){
            lblBankAC.setText(" Bank Account number Incorrect!");
        }
        else{
            lblBankAC.setText("");
        }
    }//GEN-LAST:event_txtBank_Account_NumberKeyReleased

    private void txtHealth_Plan_Beneficiary_NumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHealth_Plan_Beneficiary_NumberKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[0-9]{0,15}$";
        Pattern PHPBN = Pattern.compile(PATTERN);
        Matcher MHPBN = PHPBN.matcher(txtHealth_Plan_Beneficiary_Number.getText());
        
        if(!MHPBN.matches()){
            lblHPBN.setText("Health Plan Beneficiary Number Incorrect!");
        }
        else{
            lblHPBN.setText("");
        }
    }//GEN-LAST:event_txtHealth_Plan_Beneficiary_NumberKeyReleased

    private void txtCertificate_or_License_NumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCertificate_or_License_NumberKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[0-9]{0,15}$";
        Pattern PCLN = Pattern.compile(PATTERN);
        Matcher MCLN = PCLN.matcher(txtCertificate_or_License_Number.getText());
        
        if(!MCLN.matches()){
            lblCLN.setText("License Number Incorrect!");
        }
        else{
            lblCLN.setText("");
        }
    }//GEN-LAST:event_txtCertificate_or_License_NumberKeyReleased

    private void jButton_UploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_UploadActionPerformed
        // TODO add your handling code here:
        int Image;
            JFileChooser upload = new JFileChooser();
            Image= upload.showSaveDialog(null);
            if (Image == JFileChooser.APPROVE_OPTION){
                File biometric_Photo = upload.getSelectedFile();
                profile.setBiometric_Photo(biometric_Photo);
                
                String[] imageName = biometric_Photo.toString().split("\\\\"); 
                System.out.println(imageName);
                lblImage.setText(imageName[imageName.length - 1]);
    }
               
    }//GEN-LAST:event_jButton_UploadActionPerformed

    private void txtInternet_Protocol_AddressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInternet_Protocol_AddressKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[0-9.]{0,11}$";
        Pattern PIP = Pattern.compile(PATTERN);
        Matcher MIP = PIP.matcher(txtInternet_Protocol_Address.getText());
        
        if(!MIP.matches()){
            lblIP.setText("IP Adress Incorrect!");
        }
        else{
            lblIP.setText("");
        }
    }//GEN-LAST:event_txtInternet_Protocol_AddressKeyReleased

    private void txtGeographic_dataKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGeographic_dataKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[0-9a-zA-Z ,']{0,40}$";
        Pattern PADR = Pattern.compile(PATTERN);
        Matcher MADR = PADR.matcher(txtGeographic_data.getText());
        
        if(!MADR.matches()){
            lblGeography.setText("Address Incorrect!");
        }
        else{
            lblGeography.setText("");
        }
    }//GEN-LAST:event_txtGeographic_dataKeyReleased

    private void txtUnique_Identifying_Number_or_CodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUnique_Identifying_Number_or_CodeKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[0-9]{0,15}";
        Pattern PUIN = Pattern.compile(PATTERN);
        Matcher MUIN = PUIN.matcher(txtUnique_Identifying_Number_or_Code.getText());
        
        if(!MUIN.matches()){
        lblUIN.setText("Unique Identification Number Incorrect");
    }
        else{
            lblUIN.setText("");
        }
    }//GEN-LAST:event_txtUnique_Identifying_Number_or_CodeKeyReleased

    private void txtDevice_Identifiers_and_Serial_numberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDevice_Identifiers_and_Serial_numberKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[0-9]{0,8}";
        Pattern PDIN = Pattern.compile(PATTERN);
        Matcher MDIN = PDIN.matcher(txtDevice_Identifiers_and_Serial_number.getText());
        
        if(!MDIN.matches()){
        lblDIN.setText("Device Identification Number Incorrect");
    }
        else{
            lblDIN.setText("");
        }
    }//GEN-LAST:event_txtDevice_Identifiers_and_Serial_numberKeyReleased

    private void txtLinkedInKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLinkedInKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[0-9a-zA-Z:/.]{0,30}";
        Pattern PLink = Pattern.compile(PATTERN);
        Matcher MLink = PLink.matcher(txtLinkedIn.getText());
        
        if(!MLink.matches()){
        lblLinkedIN.setText("Linkedin URL Incorrect");
    }
        else{
            lblLinkedIN.setText("");
        }
    }//GEN-LAST:event_txtLinkedInKeyReleased

    private void txtVehicle_identifier_and_Serial_number_including_license_plateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVehicle_identifier_and_Serial_number_including_license_plateKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[A-Z0-9]{0,30}$";
        Pattern PVIN = Pattern.compile(PATTERN);
        Matcher MVIN = PVIN.matcher(txtVehicle_identifier_and_Serial_number_including_license_plate.getText());
        
        if(!MVIN.matches()){
            lblVIN_Num.setText("VIN Incorrect!");
        }
        else{
            lblVIN_Num.setText("");
        }
    }//GEN-LAST:event_txtVehicle_identifier_and_Serial_number_including_license_plateKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton jButton_Upload;
    private javax.swing.JLabel lblBankAC;
    private javax.swing.JLabel lblBank_Account_Number;
    private javax.swing.JLabel lblBiometric_Photo;
    private javax.swing.JLabel lblCLN;
    private javax.swing.JLabel lblCertificate_or_License_Number;
    private javax.swing.JLabel lblDIN;
    private javax.swing.JLabel lblDate_of_Birth;
    private javax.swing.JLabel lblDevice_Identifiers_and_Serial_number;
    private javax.swing.JLabel lblEmail_Adr;
    private javax.swing.JLabel lblEmail_address;
    private javax.swing.JLabel lblError_Name;
    private javax.swing.JLabel lblFAX;
    private javax.swing.JLabel lblFAX_number1;
    private javax.swing.JLabel lblGeographic_data1;
    private javax.swing.JLabel lblGeography;
    private javax.swing.JLabel lblHPBN;
    private javax.swing.JLabel lblHealth_Plan_Beneficiary_Number;
    private javax.swing.JLabel lblIP;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblInternet_Protocol_Address;
    private javax.swing.JLabel lblLinkedIN;
    private javax.swing.JLabel lblLinkedIn;
    private javax.swing.JLabel lblMRN;
    private javax.swing.JLabel lblMedical_record_number;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblSocial_Security_Number;
    private javax.swing.JLabel lblTele_Num;
    private javax.swing.JLabel lblTelephone_Number;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUIN;
    private javax.swing.JLabel lblUnique_Identifying_Number_or_Code;
    private javax.swing.JLabel lblVIN_Num;
    private javax.swing.JLabel lblVehicle_identifier_and_Serial_number_including_license_plate;
    private javax.swing.JTextField txtBank_Account_Number;
    private javax.swing.JTextField txtCertificate_or_License_Number;
    private javax.swing.JTextField txtDevice_Identifiers_and_Serial_number;
    private javax.swing.JTextField txtEmail_address;
    private javax.swing.JTextField txtFAX_number;
    private javax.swing.JTextField txtGeographic_data;
    private javax.swing.JTextField txtHealth_Plan_Beneficiary_Number;
    private javax.swing.JTextField txtInternet_Protocol_Address;
    private javax.swing.JTextField txtLinkedIn;
    private javax.swing.JTextField txtMedical_record_number;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSocial_Security_Number;
    private javax.swing.JTextField txtTelephone_Number;
    private javax.swing.JTextField txtUnique_Identifying_Number_or_Code;
    private javax.swing.JTextField txtVehicle_identifier_and_Serial_number_including_license_plate;
    private com.toedter.calendar.JDateChooser txtdateOfBirth;
    // End of variables declaration//GEN-END:variables
}
