/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.Profile;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.text.SimpleDateFormat;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author aishw
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    Profile profile;
    public ViewJPanel(Profile profile) throws IOException {
        initComponents();
        this.profile = profile;
        displayProfile();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblDate_of_Birth = new javax.swing.JLabel();
        lblGeographic_data1 = new javax.swing.JLabel();
        lblTelephone_Number = new javax.swing.JLabel();
        lblFAX_number1 = new javax.swing.JLabel();
        lblEmail_address = new javax.swing.JLabel();
        lblSocial_Security_Number = new javax.swing.JLabel();
        lblMedical_record_number = new javax.swing.JLabel();
        lblHealth_Plan_Beneficiary_Number = new javax.swing.JLabel();
        lblBank_Account_Number = new javax.swing.JLabel();
        lblCertificate_or_License_Number = new javax.swing.JLabel();
        lblVehicle_identifier_and_Serial_number_including_license_plate = new javax.swing.JLabel();
        lblDevice_Identifiers_and_Serial_number = new javax.swing.JLabel();
        lblLinkedIn = new javax.swing.JLabel();
        lblInternet_Protocol_Address = new javax.swing.JLabel();
        lblBiometric_Identifiers_retinalscan_or_fingerprints = new javax.swing.JLabel();
        lblUnique_Identifying_Number_or_Code = new javax.swing.JLabel();
        txtGeographic_data = new javax.swing.JTextField();
        txtdateOfBirth = new javax.swing.JTextField();
        txtTelephone_Number = new javax.swing.JTextField();
        txtFAX_number = new javax.swing.JTextField();
        txtEmail_address = new javax.swing.JTextField();
        txtSocial_Security_Number = new javax.swing.JTextField();
        txtMedical_record_number = new javax.swing.JTextField();
        txtHealth_Plan_Beneficiary_Number = new javax.swing.JTextField();
        txtBank_Account_Number = new javax.swing.JTextField();
        txtCertificate_or_License_Number = new javax.swing.JTextField();
        txtVehicle_identifier_and_Serial_number_including_license_plate = new javax.swing.JTextField();
        txtDevice_Identifiers_and_Serial_number = new javax.swing.JTextField();
        txtLinkedIn = new javax.swing.JTextField();
        txtInternet_Protocol_Address = new javax.swing.JTextField();
        txtUnique_Identifying_Number_or_Code = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        lblBiometrics = new javax.swing.JLabel();

        lblTitle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Person Profile");
        lblTitle.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 4, true));

        lblName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblName.setText("Name:");

        lblDate_of_Birth.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblDate_of_Birth.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDate_of_Birth.setText("Date_of_Birth:");

        lblGeographic_data1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblGeographic_data1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblGeographic_data1.setText("Geographic_data:");

        lblTelephone_Number.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblTelephone_Number.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTelephone_Number.setText("Telephone_Number:");

        lblFAX_number1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblFAX_number1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFAX_number1.setText("FAX_number:");

        lblEmail_address.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblEmail_address.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEmail_address.setText("Email_address:");

        lblSocial_Security_Number.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblSocial_Security_Number.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSocial_Security_Number.setText("Social_Security_Number:");

        lblMedical_record_number.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblMedical_record_number.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMedical_record_number.setText("Medical_record_number:");

        lblHealth_Plan_Beneficiary_Number.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblHealth_Plan_Beneficiary_Number.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblHealth_Plan_Beneficiary_Number.setText("Health_Plan_Beneficiary_Number:");

        lblBank_Account_Number.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblBank_Account_Number.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBank_Account_Number.setText("Bank_Account_Number:");

        lblCertificate_or_License_Number.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblCertificate_or_License_Number.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCertificate_or_License_Number.setText("Certificate_or_License_Number:");

        lblVehicle_identifier_and_Serial_number_including_license_plate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblVehicle_identifier_and_Serial_number_including_license_plate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblVehicle_identifier_and_Serial_number_including_license_plate.setText("Vehicle_identifier_and_Serial_number_including_license_plate:");

        lblDevice_Identifiers_and_Serial_number.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblDevice_Identifiers_and_Serial_number.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDevice_Identifiers_and_Serial_number.setText("Device_Identifiers_and_Serial_number:");

        lblLinkedIn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblLinkedIn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLinkedIn.setText("LinkedIn:");

        lblInternet_Protocol_Address.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblInternet_Protocol_Address.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblInternet_Protocol_Address.setText("Internet_Protocol_Address:");

        lblBiometric_Identifiers_retinalscan_or_fingerprints.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblBiometric_Identifiers_retinalscan_or_fingerprints.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBiometric_Identifiers_retinalscan_or_fingerprints.setText("Biomteric_Photo");

        lblUnique_Identifying_Number_or_Code.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblUnique_Identifying_Number_or_Code.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUnique_Identifying_Number_or_Code.setText("Unique_Identifying_Number_or_Code:");

        txtGeographic_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGeographic_dataActionPerformed(evt);
            }
        });

        txtdateOfBirth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdateOfBirthActionPerformed(evt);
            }
        });

        txtTelephone_Number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelephone_NumberActionPerformed(evt);
            }
        });

        txtFAX_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFAX_numberActionPerformed(evt);
            }
        });

        txtEmail_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmail_addressActionPerformed(evt);
            }
        });

        txtSocial_Security_Number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSocial_Security_NumberActionPerformed(evt);
            }
        });

        txtMedical_record_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedical_record_numberActionPerformed(evt);
            }
        });

        txtHealth_Plan_Beneficiary_Number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHealth_Plan_Beneficiary_NumberActionPerformed(evt);
            }
        });

        txtBank_Account_Number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBank_Account_NumberActionPerformed(evt);
            }
        });

        txtCertificate_or_License_Number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCertificate_or_License_NumberActionPerformed(evt);
            }
        });

        txtVehicle_identifier_and_Serial_number_including_license_plate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVehicle_identifier_and_Serial_number_including_license_plateActionPerformed(evt);
            }
        });

        txtDevice_Identifiers_and_Serial_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDevice_Identifiers_and_Serial_numberActionPerformed(evt);
            }
        });

        txtLinkedIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLinkedInActionPerformed(evt);
            }
        });

        txtInternet_Protocol_Address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInternet_Protocol_AddressActionPerformed(evt);
            }
        });

        txtUnique_Identifying_Number_or_Code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnique_Identifying_Number_or_CodeActionPerformed(evt);
            }
        });

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSocial_Security_Number, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMedical_record_number, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDevice_Identifiers_and_Serial_number)
                            .addComponent(lblGeographic_data1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFAX_number1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmail_address, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHealth_Plan_Beneficiary_Number)
                            .addComponent(lblBank_Account_Number)
                            .addComponent(lblCertificate_or_License_Number)
                            .addComponent(lblVehicle_identifier_and_Serial_number_including_license_plate)
                            .addComponent(lblUnique_Identifying_Number_or_Code)
                            .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDate_of_Birth, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTelephone_Number, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblInternet_Protocol_Address)
                            .addComponent(lblLinkedIn))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtBank_Account_Number, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                            .addComponent(txtFAX_number)
                            .addComponent(txtEmail_address)
                            .addComponent(txtHealth_Plan_Beneficiary_Number, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                            .addComponent(txtCertificate_or_License_Number, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                            .addComponent(txtVehicle_identifier_and_Serial_number_including_license_plate, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                            .addComponent(txtDevice_Identifiers_and_Serial_number, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                            .addComponent(txtLinkedIn, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                            .addComponent(txtInternet_Protocol_Address, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                            .addComponent(txtUnique_Identifying_Number_or_Code, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                            .addComponent(txtTelephone_Number, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                            .addComponent(txtdateOfBirth)
                            .addComponent(txtGeographic_data, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                            .addComponent(txtName)
                            .addComponent(txtMedical_record_number)
                            .addComponent(txtSocial_Security_Number))
                        .addGap(210, 210, 210)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBiometrics, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblBiometric_Identifiers_retinalscan_or_fingerprints, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 244, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblBiometrics, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblBiometric_Identifiers_retinalscan_or_fingerprints)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblGeographic_data1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGeographic_data, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblDate_of_Birth, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtdateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblTelephone_Number, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTelephone_Number, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblFAX_number1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFAX_number, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEmail_address, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmail_address, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMedical_record_number, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtMedical_record_number, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtSocial_Security_Number, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblSocial_Security_Number, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHealth_Plan_Beneficiary_Number, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHealth_Plan_Beneficiary_Number, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBank_Account_Number, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBank_Account_Number, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCertificate_or_License_Number, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCertificate_or_License_Number, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblVehicle_identifier_and_Serial_number_including_license_plate, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVehicle_identifier_and_Serial_number_including_license_plate, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtDevice_Identifiers_and_Serial_number, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLinkedIn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtInternet_Protocol_Address, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDevice_Identifiers_and_Serial_number, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblLinkedIn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblInternet_Protocol_Address, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblUnique_Identifying_Number_or_Code, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUnique_Identifying_Number_or_Code, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 172, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtGeographic_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGeographic_dataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGeographic_dataActionPerformed

    private void txtdateOfBirthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdateOfBirthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdateOfBirthActionPerformed

    private void txtTelephone_NumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelephone_NumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelephone_NumberActionPerformed

    private void txtFAX_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFAX_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFAX_numberActionPerformed

    private void txtEmail_addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmail_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmail_addressActionPerformed

    private void txtSocial_Security_NumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSocial_Security_NumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSocial_Security_NumberActionPerformed

    private void txtMedical_record_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedical_record_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedical_record_numberActionPerformed

    private void txtHealth_Plan_Beneficiary_NumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHealth_Plan_Beneficiary_NumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHealth_Plan_Beneficiary_NumberActionPerformed

    private void txtBank_Account_NumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBank_Account_NumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBank_Account_NumberActionPerformed

    private void txtCertificate_or_License_NumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCertificate_or_License_NumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCertificate_or_License_NumberActionPerformed

    private void txtVehicle_identifier_and_Serial_number_including_license_plateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVehicle_identifier_and_Serial_number_including_license_plateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVehicle_identifier_and_Serial_number_including_license_plateActionPerformed

    private void txtDevice_Identifiers_and_Serial_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDevice_Identifiers_and_Serial_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDevice_Identifiers_and_Serial_numberActionPerformed

    private void txtLinkedInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLinkedInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLinkedInActionPerformed

    private void txtInternet_Protocol_AddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInternet_Protocol_AddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInternet_Protocol_AddressActionPerformed

    private void txtUnique_Identifying_Number_or_CodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnique_Identifying_Number_or_CodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnique_Identifying_Number_or_CodeActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBank_Account_Number;
    private javax.swing.JLabel lblBiometric_Identifiers_retinalscan_or_fingerprints;
    private javax.swing.JLabel lblBiometrics;
    private javax.swing.JLabel lblCertificate_or_License_Number;
    private javax.swing.JLabel lblDate_of_Birth;
    private javax.swing.JLabel lblDevice_Identifiers_and_Serial_number;
    private javax.swing.JLabel lblEmail_address;
    private javax.swing.JLabel lblFAX_number1;
    private javax.swing.JLabel lblGeographic_data1;
    private javax.swing.JLabel lblHealth_Plan_Beneficiary_Number;
    private javax.swing.JLabel lblInternet_Protocol_Address;
    private javax.swing.JLabel lblLinkedIn;
    private javax.swing.JLabel lblMedical_record_number;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSocial_Security_Number;
    private javax.swing.JLabel lblTelephone_Number;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUnique_Identifying_Number_or_Code;
    private javax.swing.JLabel lblVehicle_identifier_and_Serial_number_including_license_plate;
    private javax.swing.JTextField txtBank_Account_Number;
    private javax.swing.JTextField txtCertificate_or_License_Number;
    private javax.swing.JTextField txtDevice_Identifiers_and_Serial_number;
    private javax.swing.JTextField txtEmail_address;
    private javax.swing.JTextField txtFAX_number;
    private javax.swing.JTextField txtGeographic_data;
    private javax.swing.JTextField txtHealth_Plan_Beneficiary_Number;
    private javax.swing.JTextField txtInternet_Protocol_Address;
    private javax.swing.JTextField txtLinkedIn;
    private javax.swing.JTextField txtMedical_record_number;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSocial_Security_Number;
    private javax.swing.JTextField txtTelephone_Number;
    private javax.swing.JTextField txtUnique_Identifying_Number_or_Code;
    private javax.swing.JTextField txtVehicle_identifier_and_Serial_number_including_license_plate;
    private javax.swing.JTextField txtdateOfBirth;
    // End of variables declaration//GEN-END:variables

    private void displayProfile() throws IOException {
        txtName.setText(profile.getName());
        txtGeographic_data.setText(profile.getGeographic_data());
        SimpleDateFormat dte = new SimpleDateFormat("MM/dd/yyyy");
        
        if (profile.getDate_of_Birth() != null) {
            txtdateOfBirth.setText(dte.format(profile.getDate_of_Birth().getTime()));
        }
        
        txtTelephone_Number.setText(Long.toString(profile.getTelephone_Number()));
        txtFAX_number.setText(Long.toString((profile.getFAX_number())));
        txtEmail_address.setText(profile.getEmail_address());
        txtSocial_Security_Number.setText(profile.getSocial_Security_Number());
        txtMedical_record_number.setText(Long.toString(profile.getMedical_record_number()));
        txtHealth_Plan_Beneficiary_Number.setText(Long.toString(profile.getHealth_Plan_Beneficiary_Number()));
        txtBank_Account_Number.setText(Long.toString(profile.getBank_Account_Number()));
        txtCertificate_or_License_Number.setText(Long.toString(profile.getCertificate_or_License_Number()));
        txtVehicle_identifier_and_Serial_number_including_license_plate.setText(profile.getVehicle_identifier_and_Serial_number_including_license_plate());
        txtDevice_Identifiers_and_Serial_number.setText(Integer.toString(profile.getDevice_Identifiers_and_Serial_number()));
        txtLinkedIn.setText(profile.getLinkedIn());
        txtInternet_Protocol_Address.setText(profile.getInternet_Protocol_Address());
        txtUnique_Identifying_Number_or_Code.setText(Long.toString(profile.getUnique_identifier()));
        
        BufferedImage uploadedPicture;
        if(profile.getBiometric_Photo()== null){
            ;
        }else{
            uploadedPicture = ImageIO.read(profile.getBiometric_Photo());
            lblBiometrics.setIcon(new ImageIcon(uploadedPicture.getScaledInstance(205,205,Image.SCALE_SMOOTH)));
        }
    }
}
